language: php
sudo: false

php:
  - 7.1
fast_finish: true

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then PHPUNIT_FLAGS="--coverage-clover=build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi
  - composer install --prefer-dist

script:
  - bin/phpunit --testsuite=unit -v $PHPUNIT_FLAGS

after_success:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then php bin/coveralls -v; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
